# Generated by Django 2.2.14 on 2020-07-14 11:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, help_text='ABSENT / COPY CASE / BLANK / specify', max_length=8)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_assmt_set_up_done', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MarksheetBulkUpdateLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.CharField(max_length=40)),
                ('division', models.CharField(max_length=40)),
                ('subject', models.CharField(max_length=40)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('updated_by', models.CharField(default='ADMIN', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PT_EVS_Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, help_text='ABSENT / COPY CASE / BLANK / specify', max_length=8)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PT_EVS_Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.CharField(choices=[('theory', 'Theory'), ('practical', 'Practical'), ('project', 'Project'), ('seminar', 'Seminar')], default='', max_length=20)),
                ('subject', models.CharField(choices=[('PT', 'Physcial Education'), ('EVS', 'Environmental Science')], max_length=5)),
                ('division', models.CharField(choices=[('', '')], max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_num', models.IntegerField()),
                ('name', models.CharField(default='', max_length=30)),
                ('division', models.CharField(choices=[('', '')], default='', max_length=5, null=True)),
                ('identifier', models.CharField(blank=True, default='', help_text='LD / Specify ', max_length=8)),
                ('sports', models.IntegerField(default=0)),
                ('vacant', models.BooleanField(default=False)),
                ('subjects', models.ManyToManyField(to='management.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='SportsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(blank=True, max_length=20)),
                ('stage', models.CharField(blank=True, max_length=20)),
                ('extra_marks', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Student')),
            ],
        ),
        migrations.CreateModel(
            name='PT_EVS_AssessmentLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_marks', models.IntegerField(null=True)),
                ('new_marks', models.IntegerField(null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('updated_by', models.CharField(default='ADMIN', max_length=20)),
                ('assmt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.PT_EVS_Assessment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='pt_evs_assessment',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.PT_EVS_Exam'),
        ),
        migrations.AddField(
            model_name='pt_evs_assessment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Student'),
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('unit_one', '1st Unit Test'), ('terminal', 'Terminal Examination'), ('unit_two', '2nd Unit Test'), ('final_theory', 'Final Examination Theory'), ('final_oral', 'Final Examination Practical_Oral')], default='', max_length=20)),
                ('division', models.CharField(choices=[('', '')], default='', max_length=5, null=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_marks', models.IntegerField(null=True)),
                ('new_marks', models.IntegerField(null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('updated_by', models.CharField(default='ADMIN', max_length=20)),
                ('assmt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.Assessment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='assessment',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Exam'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Student'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('roll_num', 'division'), name='unique_student'),
        ),
    ]
