# Generated by Django 3.0.7 on 2020-07-10 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20200710_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marksheetbulkupdatelog',
            old_name='uploaded_at',
            new_name='updated_at',
        ),
    ]
