# Generated by Django 3.0.7 on 2020-07-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20200710_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='vacant',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='identifier',
            field=models.CharField(blank=True, default='', help_text='LD / Specify ', max_length=8),
        ),
    ]
