# Generated by Django 3.0.7 on 2020-07-11 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20200710_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='division',
            field=models.CharField(choices=[('E', 'E')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='division',
            field=models.CharField(choices=[('E', 'E')], max_length=5, null=True),
        ),
    ]
