# Generated by Django 3.0.7 on 2020-07-11 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_auto_20200711_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='pt_evs_exam',
            name='division',
            field=models.CharField(choices=[('E', 'E')], max_length=5, null=True),
        ),
    ]
