# Generated by Django 3.0.7 on 2020-07-11 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_pt_evs_exam_division'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessmentlog',
            old_name='created_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='pt_evs_assessmentlog',
            old_name='created_at',
            new_name='updated_at',
        ),
    ]
