# Generated by Django 3.0.7 on 2020-07-15 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_auto_20200711_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='exam',
            name='division',
            field=models.CharField(choices=[('', ''), ('E', 'E')], default='', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='name',
            field=models.CharField(choices=[('unit_one', '1st Unit Test'), ('terminal', 'Terminal Examination'), ('unit_two', '2nd Unit Test'), ('final_theory', 'Final Examination Theory'), ('final_oral', 'Final Examination Practical_Oral')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='pt_evs_exam',
            name='division',
            field=models.CharField(choices=[('', ''), ('E', 'E')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='pt_evs_exam',
            name='exam',
            field=models.CharField(choices=[('theory', 'Theory'), ('practical', 'Practical'), ('project', 'Project'), ('seminar', 'Seminar')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='division',
            field=models.CharField(choices=[('', ''), ('E', 'E')], default='', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
