version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: ng01
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
      - ./config/nginx:/etc/nginx/conf.d
   #   - /static:/static
    depends_on:
      - web
  web:
    build: .
    container_name: dg01
    entrypoint: /entrypoint.sh
   # command: bash -c "python manage.py collectstatic --no-input"
    # depends_on:
    #   - db
    volumes:
      - ./src:/src
     # - /static:/static
    expose:
      - "8000"

  # db:
  #   image: postgres:latest
  #   command: GRANT ALL ON DATABASE postgres TO postgres;
  #   environment:
  #      - POSTGRES_DB=postgres
  #      - POSTGRES_USER=postgres
  #      - POSTGRES_PASSWORD=postgres
  #
  #   container_name: ps01
